name: Cypress Tests Execution

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3, 4, 5]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - uses: isbang/compose-action@v1.4.1
      with:
        compose-file: "${{ github.workspace }}/docker-compose.yml"
        down-flags: "--volumes"
        services: |
          ea_api
          ea_webapp
    - name: List contents of the current directory
      run: ls -la
    - name: Print working directory
      run: pwd
    - name: List contents of Cypress_test
      run: ls -la Cypress_test
    - name: Install dependencies and run Cypress tests
      working-directory: ./Cypress_test/Cypress_test
      run: |
        npm install
        npm run test
      continue-on-error: true
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: CypressResults
        path: "${{ github.workspace }}/Cypress_test/cypress/reports"
